In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import os

In [2]:
dataset = pd.read_csv('play_tennis.csv')

In [3]:
dataset

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

## Label Encoding

In [4]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()

dataset['outlook'] = Le.fit_transform(dataset['outlook'])
dataset['temp'] = Le.fit_transform(dataset['temp'])
dataset['humidity'] = Le.fit_transform(dataset['humidity'])
dataset['wind'] = Le.fit_transform(dataset['wind'])
dataset['play'] = Le.fit_transform(dataset['play'])

In [5]:
dataset

    day  outlook  temp  humidity  wind  play
0    D1        2     1         0     1     0
1    D2        2     1         0     0     0
2    D3        0     1         0     1     1
3    D4        1     2         0     1     1
4    D5        1     0         1     1     1
5    D6        1     0         1     0     0
6    D7        0     0         1     0     1
7    D8        2     2         0     1     0
8    D9        2     0         1     1     1
9   D10        1     2         1     1     1
10  D11        2     2         1     0     1
11  D12        0     2         0     0     1
12  D13        0     1         1     1     1
13  D14        1     2         0     0     0

In [6]:
y = dataset['play']
X = dataset.drop(['play'], axis=1).drop(['day'], axis=1)

In [7]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion = 'entropy')
clf = clf.fit(X, y)

In [10]:
clf.predict(X)

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [11]:
y

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: play, dtype: int32

In [14]:
clf.score(X, y)

1.0